/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.macro.mall;
import org.junit.Test;

import com.macro.mall.MallGatewayApplication;

import static org.junit.Assert.*;

public class MallGatewayApplicationTest {
    @Test public void testSomeLibraryMethod() {


    }
}
